//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobManageEntities : DbContext
    {
        public JobManageEntities()
            : base("name=JobManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Record> Record { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WantedJob> WantedJob { get; set; }
        public virtual DbSet<Dataview_1> Dataview_1 { get; set; }
        public virtual DbSet<Dateview_2> Dateview_2 { get; set; }
    }
}
