//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class WantedJob
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string City { get; set; }
        public string Industry { get; set; }
        public string PositionType { get; set; }
        public string Salary { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ResumeID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
